### ISSUE TITLE
Issue to uplaod a  pdf file in github

### ISSUE THREAD

**Issue by upadraj** [gflofst/ContainerRepo#12]
I created a PDF  file which shows how to  get started with docker  and build images, container and  form a node.js file using  docker but I don't know how to upload that file in our git  repository. I am attaching that file on this issue.
[DockerDocumentation.pdf](https://github.com/gflofst/ContainerRepo/files/5289173/DockerDocumentation.pdf)

**Comment by gflofst** [comment]
@upadhayayarajesh, there are a few options. Please search for info about adding a file to a git repo. We'll look at pull requests once you get this basic piece going. You can do it both online and from the command line. You'll need command-line access eventually, so figure that one out.

There are a lot of good step-by-step guides. If one is causing problems, please add a link and explain where the problem is so we can help you get past that.

**Comment by upadraj** [comment]
When  i try to push a PDF file in our cointainerRepo. It give an error :
Error : To https://github.com/gflofst/ContainerRepo
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/gflofst/ContainerRepo'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details

Explanation:  This issues was created because  jay first push file in  git. so, it did not let me.  which means  i need to fetch it by using the command to push it.
command: git fetch origin master
                  git merge origin master
